# Generated by Django 4.1 on 2023-09-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlineTickerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('opening', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('closing', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderbookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TickerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('opening', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('closing', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
    ]
