# Generated by Django 4.2.5 on 2023-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0002_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='tick',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
