# Generated by Django 4.2.5 on 2023-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_ticker_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='tick',
            field=models.CharField(default='', max_length=200),
        ),
    ]
