# Generated by Django 4.2.5 on 2023-09-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0004_alter_ticker_tick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='tick',
        ),
    ]
