# Generated by Django 4.1 on 2023-09-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0005_remove_ticker_tick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticker',
            new_name='TickerModel',
        ),
        migrations.RenameModel(
            old_name='Trade',
            new_name='TradeModel',
        ),
    ]
